// ============================================
// Aniston HRMS — Shared Enums
// ============================================

export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  HR = 'HR',
  MANAGER = 'MANAGER',
  EMPLOYEE = 'EMPLOYEE',
  INTERN = 'INTERN',
  GUEST_INTERVIEWER = 'GUEST_INTERVIEWER',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
  PREFER_NOT_TO_SAY = 'PREFER_NOT_TO_SAY',
}

export enum EmployeeStatus {
  ONBOARDING = 'ONBOARDING',
  ACTIVE = 'ACTIVE',
  PROBATION = 'PROBATION',
  NOTICE_PERIOD = 'NOTICE_PERIOD',
  SUSPENDED = 'SUSPENDED',
  INACTIVE = 'INACTIVE',
  TERMINATED = 'TERMINATED',
  ABSCONDED = 'ABSCONDED',
}

export enum WorkMode {
  OFFICE = 'OFFICE',
  HYBRID = 'HYBRID',
  FIELD_SALES = 'FIELD_SALES',
  PROJECT_SITE = 'PROJECT_SITE',
  REMOTE = 'REMOTE',
}

export enum AttendanceStatus {
  PRESENT = 'PRESENT',
  ABSENT = 'ABSENT',
  HALF_DAY = 'HALF_DAY',
  HOLIDAY = 'HOLIDAY',
  WEEKEND = 'WEEKEND',
  ON_LEAVE = 'ON_LEAVE',
  WORK_FROM_HOME = 'WORK_FROM_HOME',
}

export enum AttendanceSource {
  GEOFENCE_AUTO = 'GEOFENCE_AUTO',
  MANUAL_APP = 'MANUAL_APP',
  MANUAL_HR = 'MANUAL_HR',
  QR_CODE = 'QR_CODE',
  BIOMETRIC = 'BIOMETRIC',
}

export enum BreakType {
  LUNCH = 'LUNCH',
  SHORT = 'SHORT',
  PRAYER = 'PRAYER',
  CUSTOM = 'CUSTOM',
}

export enum LeaveRequestStatus {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  MANAGER_APPROVED = 'MANAGER_APPROVED',
  APPROVED = 'APPROVED',
  APPROVED_WITH_CONDITION = 'APPROVED_WITH_CONDITION',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum DocumentType {
  AADHAAR = 'AADHAAR',
  PAN = 'PAN',
  PASSPORT = 'PASSPORT',
  VOTER_ID = 'VOTER_ID',
  DRIVING_LICENSE = 'DRIVING_LICENSE',
  DEGREE_CERTIFICATE = 'DEGREE_CERTIFICATE',
  TENTH_CERTIFICATE = 'TENTH_CERTIFICATE',
  TWELFTH_CERTIFICATE = 'TWELFTH_CERTIFICATE',
  POST_GRADUATION_CERTIFICATE = 'POST_GRADUATION_CERTIFICATE',
  EXPERIENCE_LETTER = 'EXPERIENCE_LETTER',
  OFFER_LETTER_DOC = 'OFFER_LETTER_DOC',
  JOINING_LETTER = 'JOINING_LETTER',
  RELIEVING_LETTER = 'RELIEVING_LETTER',
  BANK_STATEMENT = 'BANK_STATEMENT',
  CANCELLED_CHEQUE = 'CANCELLED_CHEQUE',
  SALARY_SLIP_DOC = 'SALARY_SLIP_DOC',
  PHOTO = 'PHOTO',
  SIGNATURE = 'SIGNATURE',
  RESIDENCE_PROOF = 'RESIDENCE_PROOF',
  PROFESSIONAL_CERTIFICATION = 'PROFESSIONAL_CERTIFICATION',
  OTHER = 'OTHER',
}

export enum DocumentStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  FLAGGED = 'FLAGGED',
  EXPIRED = 'EXPIRED',
  ISSUED = 'ISSUED',
}

export enum JobType {
  FULL_TIME = 'FULL_TIME',
  PART_TIME = 'PART_TIME',
  CONTRACT = 'CONTRACT',
  INTERNSHIP = 'INTERNSHIP',
  RESEARCH = 'RESEARCH',
}

export enum JobStatus {
  DRAFT = 'DRAFT',
  OPEN = 'OPEN',
  ON_HOLD = 'ON_HOLD',
  CLOSED = 'CLOSED',
}

export enum ApplicationStatus {
  APPLIED = 'APPLIED',
  SCREENING = 'SCREENING',
  ASSESSMENT = 'ASSESSMENT',
  INTERVIEW_1 = 'INTERVIEW_1',
  INTERVIEW_2 = 'INTERVIEW_2',
  HR_ROUND = 'HR_ROUND',
  FINAL_ROUND = 'FINAL_ROUND',
  OFFER = 'OFFER',
  OFFER_ACCEPTED = 'OFFER_ACCEPTED',
  JOINED = 'JOINED',
  REJECTED = 'REJECTED',
  WITHDRAWN = 'WITHDRAWN',
}

export enum ApplicationSource {
  PORTAL = 'PORTAL',
  NAUKRI = 'NAUKRI',
  LINKEDIN = 'LINKEDIN',
  REFERENCE = 'REFERENCE',
  CAMPUS = 'CAMPUS',
  WALK_IN = 'WALK_IN',
}

export enum OfferStatus {
  DRAFT = 'DRAFT',
  SENT = 'SENT',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  NEGOTIATING = 'NEGOTIATING',
  EXPIRED = 'EXPIRED',
}

export enum PayrollRunStatus {
  DRAFT = 'DRAFT',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  LOCKED = 'LOCKED',
}

export enum TaxRegime {
  OLD_REGIME = 'OLD_REGIME',
  NEW_REGIME = 'NEW_REGIME',
}

export enum SalaryTemplateType {
  INTERN = 'INTERN',
  FULL_TIME = 'FULL_TIME',
  CONTRACT = 'CONTRACT',
  CUSTOM = 'CUSTOM',
}

export enum SalaryChangeType {
  INITIAL = 'INITIAL',
  REVISION = 'REVISION',
  PROMOTION = 'PROMOTION',
  CORRECTION = 'CORRECTION',
  TEMPLATE_APPLIED = 'TEMPLATE_APPLIED',
}

export enum PoliceVerificationStatus {
  PENDING = 'PENDING',
  INITIATED = 'INITIATED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum AssetCategory {
  LAPTOP = 'LAPTOP',
  MOBILE = 'MOBILE',
  SIM_CARD = 'SIM_CARD',
  ACCESS_CARD = 'ACCESS_CARD',
  VISITING_CARD = 'VISITING_CARD',
  MONITOR = 'MONITOR',
  OTHER = 'OTHER',
}

export enum AssetStatus {
  AVAILABLE = 'AVAILABLE',
  ASSIGNED = 'ASSIGNED',
  MAINTENANCE = 'MAINTENANCE',
  RETIRED = 'RETIRED',
}

export enum PolicyCategory {
  HR_GENERAL = 'HR_GENERAL',
  LEAVE = 'LEAVE',
  HYBRID = 'HYBRID',
  WORK_MANAGEMENT = 'WORK_MANAGEMENT',
  ESCALATION = 'ESCALATION',
  IT = 'IT',
  CODE_OF_CONDUCT = 'CODE_OF_CONDUCT',
  HEALTH_SAFETY = 'HEALTH_SAFETY',
}

export enum LetterType {
  OFFER_LETTER = 'OFFER_LETTER',
  JOINING_LETTER = 'JOINING_LETTER',
  EXPERIENCE_LETTER = 'EXPERIENCE_LETTER',
  RELIEVING_LETTER = 'RELIEVING_LETTER',
  SALARY_SLIP_LETTER = 'SALARY_SLIP_LETTER',
  PROMOTION_LETTER = 'PROMOTION_LETTER',
  WARNING_LETTER = 'WARNING_LETTER',
  APPRECIATION_LETTER = 'APPRECIATION_LETTER',
  CUSTOM = 'CUSTOM',
}

export enum GeofenceType {
  OFFICE = 'OFFICE',
  CLIENT_SITE = 'CLIENT_SITE',
  RESTRICTED = 'RESTRICTED',
}

export enum InvitationStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  EXPIRED = 'EXPIRED',
}

export enum AiProvider {
  DEEPSEEK = 'DEEPSEEK',
  OPENAI = 'OPENAI',
  ANTHROPIC = 'ANTHROPIC',
  GEMINI = 'GEMINI',
  CUSTOM = 'CUSTOM',
}

export enum McqCategory {
  INTELLIGENCE = 'INTELLIGENCE',
  INTEGRITY = 'INTEGRITY',
  ENERGY = 'ENERGY',
}

export enum PublicAppStatus {
  SUBMITTED = 'SUBMITTED',
  SHORTLISTED = 'SHORTLISTED',
  INTERVIEW_SCHEDULED = 'INTERVIEW_SCHEDULED',
  SELECTED = 'SELECTED',
  REJECTED = 'REJECTED',
  ON_HOLD = 'ON_HOLD',
}

export enum InterviewRoundType {
  HR = 'HR',
  MANAGER = 'MANAGER',
  SUPERADMIN = 'SUPERADMIN',
}

export enum RoundStatus {
  PENDING_ROUND = 'PENDING_ROUND',
  IN_PROGRESS_ROUND = 'IN_PROGRESS_ROUND',
  COMPLETED_ROUND = 'COMPLETED_ROUND',
}

export enum WalkInStatus {
  WAITING = 'WAITING',
  IN_INTERVIEW = 'IN_INTERVIEW',
  ON_HOLD = 'ON_HOLD',
  SELECTED = 'SELECTED',
  REJECTED = 'REJECTED',
  COMPLETED = 'COMPLETED',
  NO_SHOW = 'NO_SHOW',
}

export enum ShiftType {
  OFFICE = 'OFFICE',
  FIELD = 'FIELD',
  HYBRID = 'HYBRID',
}

// ============================================
// Enterprise Attendance Enums
// ============================================

export enum AnomalyType {
  LATE_ARRIVAL = 'LATE_ARRIVAL',
  EARLY_EXIT = 'EARLY_EXIT',
  MISSING_PUNCH = 'MISSING_PUNCH',
  INSUFFICIENT_HOURS = 'INSUFFICIENT_HOURS',
  OUTSIDE_GEOFENCE = 'OUTSIDE_GEOFENCE',
  DUPLICATE_PUNCH = 'DUPLICATE_PUNCH',
  SUSPICIOUS_GAP = 'SUSPICIOUS_GAP',
  LEAVE_OVERLAP = 'LEAVE_OVERLAP',
  HOLIDAY_ATTENDANCE = 'HOLIDAY_ATTENDANCE',
  LOCATION_MISMATCH = 'LOCATION_MISMATCH',
  UNAPPROVED_REMOTE = 'UNAPPROVED_REMOTE',
  POLICY_BREACH = 'POLICY_BREACH',
  GPS_SPOOF = 'GPS_SPOOF',
}

export enum AnomalySeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum AnomalyResolution {
  PENDING = 'PENDING',
  AUTO_RESOLVED = 'AUTO_RESOLVED',
  MANAGER_APPROVED = 'MANAGER_APPROVED',
  HR_APPROVED = 'HR_APPROVED',
  REJECTED = 'REJECTED',
  DISMISSED = 'DISMISSED',
}

export enum LocationCompliance {
  INSIDE_GEOFENCE = 'INSIDE_GEOFENCE',
  OUTSIDE_GEOFENCE = 'OUTSIDE_GEOFENCE',
  APPROVED_FIELD_SITE = 'APPROVED_FIELD_SITE',
  REMOTE_APPROVED = 'REMOTE_APPROVED',
  UNKNOWN = 'UNKNOWN',
}

export enum RegularizationStatus {
  PENDING = 'PENDING',
  MANAGER_REVIEWED = 'MANAGER_REVIEWED',
  HR_REVIEWED = 'HR_REVIEWED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum AssetCondition {
  EXCELLENT = 'EXCELLENT',
  GOOD = 'GOOD',
  FAIR = 'FAIR',
  DAMAGED = 'DAMAGED',
  LOST = 'LOST',
}

export enum WaTemplateType {
  JOB_LINK = 'JOB_LINK',
  ONBOARDING_INVITE = 'ONBOARDING_INVITE',
  OFFER_LETTER = 'OFFER_LETTER',
  LEAVE_APPROVED = 'LEAVE_APPROVED',
  GENERAL = 'GENERAL',
}

export enum WaMessageStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  READ = 'READ',
  FAILED = 'FAILED',
  RECEIVED = 'RECEIVED',
}

export enum WaMessageDirection {
  OUTBOUND = 'OUTBOUND',
  INBOUND = 'INBOUND',
}

export enum WaConversationStatus {
  OPEN = 'OPEN',
  CLOSED = 'CLOSED',
  ARCHIVED = 'ARCHIVED',
}

export enum WaContactSource {
  MANUAL = 'MANUAL',
  WHATSAPP_IMPORT = 'WHATSAPP_IMPORT',
  EMPLOYEE = 'EMPLOYEE',
  ONBOARDING = 'ONBOARDING',
  APPLICATION = 'APPLICATION',
}

export enum KycStatus {
  PENDING = 'PENDING',
  SUBMITTED = 'SUBMITTED',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum ExitAccessFeature {
  VIEW_DASHBOARD = 'canViewDashboard',
  VIEW_PAYSLIPS = 'canViewPayslips',
  DOWNLOAD_PAYSLIPS = 'canDownloadPayslips',
  VIEW_ATTENDANCE = 'canViewAttendance',
  MARK_ATTENDANCE = 'canMarkAttendance',
  APPLY_LEAVE = 'canApplyLeave',
  VIEW_LEAVE_BALANCE = 'canViewLeaveBalance',
  VIEW_DOCUMENTS = 'canViewDocuments',
  DOWNLOAD_DOCUMENTS = 'canDownloadDocuments',
  VIEW_HELPDESK = 'canViewHelpdesk',
  CREATE_TICKET = 'canCreateTicket',
  VIEW_ANNOUNCEMENTS = 'canViewAnnouncements',
  VIEW_PROFILE = 'canViewProfile',
}

export enum InterviewerType {
  INTERNAL = 'INTERNAL',
  EXTERNAL = 'EXTERNAL',
  HR = 'HR',
  DEPARTMENT_HEAD = 'DEPARTMENT_HEAD',
}

export enum InterviewRecommendation {
  STRONG_YES = 'STRONG_YES',
  YES = 'YES',
  MAYBE = 'MAYBE',
  NO = 'NO',
  STRONG_NO = 'STRONG_NO',
}

export enum InterviewRoundStatus {
  PENDING = 'PENDING',
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum InterviewRoundResult {
  PASSED = 'PASSED',
  FAILED = 'FAILED',
  ON_HOLD = 'ON_HOLD',
}

export enum BulkUploadStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum ResumeItemStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SCORED = 'SCORED',
  FAILED = 'FAILED',
}
